---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
Sys.setlocale("LC_TIME", "English")
require(lattice)

rawData = read.csv("activity.csv", stringsAsFactors = FALSE)
rawData$date = as.Date(rawData$date, "%Y-%m-%d")
```



## What is mean total number of steps taken per day?
```{r}
dailySteps = tapply(as.numeric(rawData$steps), rawData$date, sum, na.rm = TRUE)
hist(dailySteps)

summary(dailySteps) # Contains median and mean
```



## What is the average daily activity pattern?
```{r}
meanTimeSteps = tapply(as.numeric(rawData$steps), rawData$interval, mean, na.rm = TRUE)
plot(meanTimeSteps, type = "l", xlab = "Time interval", ylab = "Mean steps")
```

```{r}
## Get the 5-minute interval name which contains the maximum number of steps.
names(which(meanTimeSteps == max(meanTimeSteps)))
```



## Imputing missing values
```{r}
## Calculate total number of missing values in the dataset.
sum(is.na(rawData))

## NAs are replaced by the means for that 5-minute interval
adjData = rawData
adjData$steps[is.na(adjData$steps)] = tapply(as.numeric(adjData$steps), adjData$interval, mean, na.rm = TRUE)

adjDailySteps = tapply(as.numeric(adjData$steps), adjData$date, sum, na.rm = TRUE)
## histogram
hist(adjDailySteps)
## Mean and median
summary(adjDailySteps)
```

Impact: the overall numbers of steps are increased.

## Are there differences in activity patterns between weekdays and weekends?
```{r}
weekdayData = adjData[which(weekdays(adjData$date) %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")), ]
weekdayTimeSteps = tapply(as.numeric(weekdayData$steps), weekdayData$interval, mean)
weekdayTimeSteps = data.frame(interval = names(weekdayTimeSteps), steps = weekdayTimeSteps, isweekday = rep("weekday", length(weekdayTimeSteps)), stringsAsFactors = FALSE)
weekdayTimeSteps$interval = as.numeric(weekdayTimeSteps$interval)

weekendData = adjData[which(weekdays(adjData$date) %in% c("Saturday", "Sunday")), ]
weekendTimeSteps = tapply(as.numeric(weekendData$steps), weekendData$interval, mean)
weekendTimeSteps = data.frame(interval = names(weekendTimeSteps), steps = weekendTimeSteps, isweekday = rep("weekend", length(weekendTimeSteps)), stringsAsFactors = FALSE)
weekendTimeSteps$interval = as.numeric(weekendTimeSteps$interval)

timeSteps = rbind(weekdayTimeSteps, weekendTimeSteps)

xyplot(steps~interval | isweekday, data = timeSteps, type = "l", layout = c(1,2))
```

